#!/bin/bash

LOCK=/tmp/eww_bar.lock
if [ -f "$LOCK" ]; then
    eww close bar > /dev/null
    bspc config bottom_padding 3
    dunstify -t 1000 --replace=1132 "Eww" "Bar closed..."
    rm $LOCK
else
    eww open-many bar && bspc config -m HDMI2 bottom_padding 48
    dunstify -t 1000 --replace=1132 "Eww" "Bar launched..."
    touch $LOCK
fi
