#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep "HDMI2 connected" ) ]];
    then
	xrandr --output eDP1 --primary --mode 1366x768 --pos 0x635 --rotate normal --output DP1 --off --output HDMI1 --off --output HDMI2 --mode 1920x1080 --pos 1366x0 --rotate normal --output VIRTUAL1 --off
	bspc monitor eDP1 -d I II III IV V
	bspc monitor HDMI2 -d VI VII VIII IX X
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc config border_width         1
bspc config focused_border_color "#97bfae"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
picom -b
/usr/lib/polkit-gnome/polit-gnome-authentication-agent-1 &
nitrogen --restore &
dunst &
eww daemon &

